component: http
name: cfs-server-daily

inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs12.16
    framework: egg
    name: ${name}
  apigw:
    protocols:
      - http
      - https

app: cfs-server
stage: daily